### ISSUE TITLE
Unable to run v3c on Ubuntu 20.04.2 on Windows 10

### ISSUE THREAD

**Issue by ThomasBHickey** [titzer/virgil#109]
Wanted to try Virgil on Advent of Code 2022, but can't get started (and running out of time!):

What I see:
 
~/Thom/GitHub/virgil/apps/HelloWorld$ v3c HelloWorld.v3
-bash: /home/thom/Thom/GitHub/virgil/bin/v3c: cannot execute binary file: Exec format error

Some things I've looked at: 

~/Thom/GitHub/virgil/bin/stable/x86-linux$ file Aeneas
Aeneas: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, no section header

 ./Aeneas
-bash: ./Aeneas: cannot execute binary file: Exec format error

Must be something simple?

--Th

**Comment by titzer** [comment]
It looks like it might be sensing the host platform incorrectly. Are you running on x86-linux or x86-64-linux? Try doing a `make clean` and running `v3c` again. What is the output of `uname -a` for you?

**Comment by ThomasBHickey** [comment]
Linux DESKTOP-6R1F0BS 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

32 vs 64 is probably the issue.  Right now I'm trying to get my m4/wat code to work for AOC 2022, but I'll get back to this

Thanks!

**Comment by titzer** [comment]
I'm going to close this issue because at the moment it's not actionable. Feel free to reopen if you have new information or any suggestion on what/how to fix.
