### ISSUE TITLE
docs / release?

### ISSUE THREAD

**Issue by andychu** [titzer/virgil#15]
I read the Virgil III paper, and it seems like a really cool mix of high level features and low level code -- the holy grail :)

I tried it out and made an `echo.v3` program run under the interpreter, ran a jar, and ran an x86 executable.

Any plans for a release or maybe a README describing how to use it?  I had to read the shell scripts to figure out how to invoke it. 

I'm interested in the compile-time metaprogramming among other things.

It looks like it is still aimed more at embedded systems, since there's no module system or C integration?  (as far as I can see)

**Comment by titzer** [comment]
Hi Andy,

You're right of course :-) The documentation rotted a bit. It used to look fairly decent years ago when it was hosted on code.google.com, but I haven't lifted a finger to update it to GitHub MD yet.

**Comment by titzer** [comment]
I've imported some documentation from the old wiki, updated it, and added a README.
