### ISSUE TITLE
non-void main in wasm - expected 1 elements on the stack for fallthru to @1, found 2

### ISSUE THREAD

**Issue by diakopter** [titzer/virgil#19]
While trying to diagnose the remainder of #18, I changed hello-v3.v3 to read:
```
def main() -> int {
	System.puts("Hello world!\n");
	return 33;
}
```
and got this output after compilation:
```
user@host009:~/src/virgil/bin/dev$ wave hello-v3.wasm
<unknown>:-1: Uncaught CompileError: WebAssembly.Module(): Compiling wasm function
 "wasm-function[4]" failed: expected 1 elements on the stack for fallthru to @1, found 2 @+232
ERROR: could not compile hello-v3.wasm
255 user@host009:~/src/virgil/bin/dev$
```

**Comment by titzer** [comment]
This is because your main function does not accept parameters, and the stub generated to call `RiRuntime.init` and your main fails. I should add a check for this, but you can fix this problem by having your main accept an `Array<string>` as a parameter.

**Comment by titzer** [comment]
Fixed this recently. There should now be a compile error for incorrect main signatures, and all legal combinations should work.
