### ISSUE TITLE
Git conflict markers in tests

### ISSUE THREAD

**Issue by k-sareen** [titzer/virgil#227]
Hello! Been a while. Just pulled master today and I saw [this](https://github.com/titzer/virgil/commit/65b6be04304b0d079dd71551dd5159719966fad7) commit that seemed to check in the git conflict markers into test files [here](https://github.com/titzer/virgil/blob/a115ff1232d776185e3f9172434e68ab285d64b8/aeneas/test/NumberParserTest.v3) and [here](https://github.com/titzer/virgil/blob/a115ff1232d776185e3f9172434e68ab285d64b8/test/core/seman/lit_width01.v3)? I presume that was a mistake.

I'm not sure why the test script doesn't die?

**Comment by titzer** [comment]
Ah, shoot. I had a merge rebase issue and thought I had fixed that. Yeah, somehow the unit tests don't fail the CI; similar issue to parser failures not generating a non-zero exit code. I'll fix the conflict markers in a sec.

**Comment by k-sareen** [comment]
CI is just piggy-backing off `test/all.bash` so the underlying issue is likely there.

**Comment by k-sareen** [comment]
Also https://github.com/titzer/virgil/commit/44bda5f28bb9ebdc998d3fb9da15c8c3171cb8a5 only fixed one file. [This](https://github.com/titzer/virgil/blob/a115ff1232d776185e3f9172434e68ab285d64b8/test/core/seman/lit_width01.v3) file still has the markers checked in.

**Comment by titzer** [comment]
Going to close this; probably should be a separate issue for the unit tests not failing CI.
