### ISSUE TITLE
build scripts & test harness in Virgil?

### ISSUE THREAD

**Issue by diakopter** [titzer/virgil#24]
What do you think about having the build & test scripts written in Virgil?  I'm happy to toy around with it if it's a valid endeavor.

**Comment by titzer** [comment]
I generally like the idea of reducing dependencies on other software. The problem with building and testing though a.) trusting some base-level software to properly report tests passed/failed and b) bringing Virgil to a new platform.

That said, I really am not a big fan of test/bin/src/execute-arch-posix.c, which is essentially a C program trusted to fork and execute native binaries for testing. There is a lot of duplication with parsing the input/output spec of tests that is a pain and maybe better written in another language.

**Comment by titzer** [comment]
One thing that would be useful though, would be to convert the test suite to universally use the `progress` program output. It's just a standardized simple text format for all test output that can be processed to produced the "pretty" outputs seen in the test scripts now. Currently, each kind of test has its own ad hoc test output format that is shoehorned into something OK-looking.

**Comment by titzer** [comment]
I've now converted the test suite to use the `progress` program output and generally improved the situation.

I think I'll stick with `bash` for tests now.
