### ISSUE TITLE
error in test/all.bash with x86-64

### ISSUE THREAD

**Issue by diakopter** [titzer/virgil#43]
`user@DESKTOP-3H33NCK:~/src/virgil$ bash test/all.bash`:

![image](https://user-images.githubusercontent.com/50262/110394227-b0a09980-8031-11eb-8bff-70667ab0a3fa.png)

**Comment by titzer** [comment]
Yeah, I think I added the new target before revving stable (the error is because the stable compiler does not have an x86-64 target and that is being used for the first lib tests before the first bootstrap).

**Comment by titzer** [comment]
Remove the new platform from the tests until stable rev.
