### ISSUE TITLE
Looks great!

### ISSUE THREAD

**Issue by eboatwright** [titzer/virgil#51]
Very RUST-y :) (My favorite programming language)

**Comment by titzer** [comment]
Thanks! Feel free to post comments or suggestions. I'll leave this issue open for a while if you want to post here.

Other people have inquired about Rust integration. I added a project description [here](https://github.com/titzer/student-projects#integrate-virgil-and-rust---virgilrust-medium-difficulty-high-novelty-high-priority).

**Comment by eboatwright** [comment]
Awesome!

**Comment by eboatwright** [comment]
Is there a way to get input from the console?

**Comment by eboatwright** [comment]
Also, what about adding two strings together?

**Comment by titzer** [comment]
You can indeed read input from stdin, and from files. There is a component `System` that has an implementation on every platform (even the interpreter). E.g. here is the implementation on x86-linux: https://github.com/titzer/virgil/blob/master/rt/x86-linux/System.v3

You can do basic read/writing of file descriptors through those calls.

As for strings, they are just arrays of characters; they don't have any special methods. But there is `Arrays.concat` that will create a new array by copying two strings. https://github.com/titzer/virgil/blob/master/lib/util/Arrays.v3#L66

**Comment by eboatwright** [comment]
Ok great! Virgil is shaping up to be a great programming language! :smile:
