### ISSUE TITLE
Idea: TS Transpiler to Virgil

### ISSUE THREAD

**Issue by syrusakbary** [titzer/virgil#66]
Since TypeScript can have programs with fully statically defined types, I wonder if it may be possible to have a transpiler that transforms TS codebases into Virgil and then we use it to compile to very lean Wasm code.

There are already some projects that do static compilation of Typescript:
* AssemblyScript (subset of TS) https://www.assemblyscript.org/
* TypescriptCompiler (compiles TS to LLVM IR) https://github.com/ASDAlexander77/TypeScriptCompiler
* Microsoft's PXT https://github.com/microsoft/pxt/tree/master/pxtcompiler (it has an interpreter, an optimal JS converter and also supports ARM Thumb compilation)

Could it be possible to achieve with Virgil? Where you think may be the limitations?

**Comment by syrusakbary** [comment]
Some context: why this may be useful?
If we are able to transpile TS projects into Virgil, and Virgil can be self-hosted and Wasm/WASI powered... then we can have a full TS to Wasm compiler almost for free :)

**Comment by MaxGraey** [comment]
> f we are able to transpile TS projects into Virgil, and Virgil can be self-hosted and Wasm/WASI powered... then we can have a full TS to Wasm compiler (that just requires a WASI runtime!) almost for free :)

So you're suggesting take a AssemblyScript which can compile to WebAssembly with WASI reuse it somehow for transpile to Virgil and compile to WebAssembly with WASI? Does it make sense at all?

**Comment by syrusakbary** [comment]
> Foremost, there is no TypeScript specification (it was once tried to be created and maintained but later abandoned)

Yup, you are right on this one. What I was referring on this, is: if passes the tests then it "complies with the spec".
 
> Second, TypeScript as it exists does not allow it to be compiled into AOT

I kindly disagree. I don't see any reason for which it would be impossible to compile strict Typescript to Wasm (please see PXT or TypescriptCompiler links I previously posted). It's true that to make that possible, the perceived speed improvements of running such compiled Wasm file in JIT-able JS engines will be negligible (that is, if we run `TS` directly vs `TS -> Wasm` in a JS jitted browser).
However, in non-JIT environments (such as QuickJS, or any other JS runtime compilable to Wasm), the speed improvements of running TS compiled to Wasm vs Running it inside a JS environment can be an order of magnitude better.

> Most of the projects written in TS and published in npm are actually JavaScript + d.ts file

Yup, this one is one that is going to be hard to pass by!

**Comment by titzer** [comment]
I agree that a TypeScript -> Virgil transpiler would be a very involved project. It seems like TypeScript -> AssemblyScript -> Wasm captures the statically-typeable part of TS well.

**Comment by diakopter** [comment]
also, virgil would need a much more robust GC, regardless of "static typeability"

**Comment by titzer** [comment]
I'm going to close this because I don't think it's actionable in the Virgil repo. A TS transpiler would be a significant undertaking, as discussed above, and I think that undertaking wouldn't necessarily live best in this repository.

Thanks for the idea, keep them coming!

**Comment by syrusakbary** [comment]
Makes sense! I tried to play a bit with WASI as target for Virgil a few weeks ago but it was not fully working. Will try to open more issues/suggestions soon!
