### ISSUE TITLE
Built in interpretor

### ISSUE THREAD

**Issue by wenq1** [titzer/virgil#67]
What IR does the built-in interpreter interpret? Is is wasm? It seems that this basic question is left untouched in the documentation which I have dug through multiple times.

**Comment by titzer** [comment]
It's an internal format similar to bytecode, but every instruction is represented as an object. 

Internally It's called "IC" (for interpreter code) and is here: https://github.com/titzer/virgil/tree/master/aeneas/src/ic

The Virgil compiler only generates IC code from SSA, which it can do before or after the reachability/specialization phase. The translation from SSA to IC is here: https://github.com/titzer/virgil/blob/master/aeneas/src/ssa/SsaIcGen.v3

**Comment by wenq1** [comment]
thanks for the clarification
