### ISSUE TITLE
x86-64-linux executables exit with random non-zero exit codes

### ISSUE THREAD

**Issue by srackham** [titzer/virgil#78]
This is an odd one: x86-64-linux executables sometimes return a (seemingly random) non-zero exit code from the main() function:

```sh
$ cat hello.v3 && v3c-x86-64-linux hello.v3 && ./hello; echo $?
def main() {
  System.puts("Hello World\n");
}
Hello World
216
```
If a second print statement is added the exit code is zero:

```sh
$ cat hello.v3 && v3c-x86-64-linux hello.v3 && ./hello; echo $?
def main() {
  System.puts("Hello World\n");
  System.puts("Hello World\n");
}
Hello World
Hello World
0
```

Explicitly returning an exit code from main() seems to resolve the problem:

```sh
$ cat hello.v3 && v3c-x86-64-linux hello.v3 && ./hello; echo $?
def main() -> int {
  System.puts("Hello World\n");
  return 0;
}
Hello World
0
```

The x86-linux target does not seem to exhibit this behaviour.

```sh
$ cat hello.v3 && v3c-x86-linux hello.v3 && ./hello; echo $? 
def main() {
  System.puts("Hello World\n");
}
Hello World
0
```

**Comment by titzer** [comment]
Ah, nice catch. There was a check for this but the logic was broken, so it was exiting with whatever happened to be in `rax`.

Fixed in https://github.com/titzer/virgil/commit/15c489e792016a624660641452344ba9b0b0dd62.

**Comment by srackham** [comment]
Verified! Thanks for the super-fast bugfix.
