### ISSUE TITLE
Support floating point

### ISSUE THREAD

**Issue by GoogleCodeExporter** [titzer/virgil#8]
```
Language or Compiler Enhancement?
===========================

Language and Compiler

Justification (summary of perceived benefit)
===============================

Support for 32 and 64 bit floating point numbers is necessary to perform all 
manner of scientific and graphics calculations.

Impact estimate (select one)
----------------------
3 - large
================

Priority (select one)
----------------------
2 - medium
================


```

Original issue reported on code.google.com by `titzer@google.com` on 24 Jan 2013 at 7:29

**Comment by titzer** [comment]
Floating point support is complete on the JVM and WASM targets now.
Still more work for x86 targets.

**Comment by k-sareen** [comment]
Close issue?

**Comment by titzer** [comment]
I will close the issue when I've finished implementing it in the IC interpreter.

**Comment by titzer** [comment]
Done in https://github.com/titzer/virgil/commit/09cadf5aa33ae25b5ed925e0ef11379f51d1332e.

Will close when promoted to stable.

**Comment by titzer** [comment]
Finished in https://github.com/titzer/virgil/commit/02ed313480b5968d51b29c3fffd670c3094a755b

Thanks @k-sareen for the x86 backend work!
