### ISSUE TITLE
Virgil interpreter does not return main() exit code

### ISSUE THREAD

**Issue by srackham** [titzer/virgil#88]
Is there a reason the exit code returned by the interpreter is always zero? For example:

```sh
$ cat t.v3
def main() -> int {
        return 1;
}

$ v3c run t.v3

$ echo $?
0

$ v3c-x86-linux t.v3

$ ./t

$ echo $?
1
```

**Comment by titzer** [comment]
I hadn't noticed until now. Fixed. Thanks!

**Comment by titzer** [comment]
BTW a few months back I added the `v3i` script as a shorthand for `v3c -run`. I was considering even adding a special build to generate a smaller binary that includes only the interpreter, and the command would make that easier.

**Comment by srackham** [comment]
Thanks for the super-quick bug-fix. It works with `v3i` but not with `v3c run`:

```sh
$ v3c --version
Aeneas III-7.1536: no input files

$ cat t.v3
def main() -> int {
        return 1;
}

$ v3i t.v3

$ echo $?
1

$ v3c run t.v3

$ echo $?
0
```

**Comment by titzer** [comment]
It should be `v3c -run` above.

I just noticed that `v3c run`--in fact `v3c anything_that_doesnt_end_in_dot_v3` doesn't actually do anything. That's a bug too!

**Comment by srackham** [comment]
Ah, my confusing `virgil` and `v3c` commands was a fortuitous mistake :-) Thanks for clearing that up.

**Comment by titzer** [comment]
The `virgil` script doesn't get much love, TBH. I had intended it to be a bit like the `go` command, but I end up debugging the compiler itself so much that I rarely use it.

**Comment by srackham** [comment]
Don't sweat the small stuff, it can be taken care of later -- just carry on with the hard stuff.
