### ISSUE TITLE
what's `Exprs` in the grammar?

### ISSUE THREAD

**Issue by csmoe** [titzer/virgil#93]
https://github.com/titzer/virgil/blob/ef8e88d2333c1ad1181ddb75f73dafc858b7449b/doc/virgil-grammar.ebnf#L66

`Exprs` node seems undefined.

**Comment by titzer** [comment]
Ah, I just noticed this. It's a comma-separated list of expressions. (I should probably actually generate a parser from EBNF and use it to debug it...)

Thanks!
